### ISSUE TITLE
Move COLOR_COUNT macro to top of file

### ISSUE THREAD

**Issue by someStranger8** [someStranger8/Vex-Competition#17]
For more clean code

**Comment by Icosa-dev** [comment]
Macros are preprocessor directives and can go anywhere in code. It makes more sense to define them where they are needed instead of all clumped at the top. 

Better idea: turn every line of source code into a macro and define it in a file that is .gitignore'd

**Comment by someStranger8** [comment]
bet

**Comment by someStranger8** [comment]
Fixed in latest PR
